### ISSUE TITLE
Encountering Context timeout in tests

### ISSUE THREAD

**Issue by matthewmcneely** [dgraph-io/travel#21]
```
$ go version
go version go1.14.3 darwin/amd64
$ uname -a
Darwin grigora.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_6
$ sysctl hw.model
hw.model: Macmini8,1
```

Running `make test` results in a Context timeout:

```
<snip>
=== RUN   TestMutate/city
    TestMutate/city: mutate_test.go:33: Given the need to be able to validate storing a city.
    TestMutate/city: mutate_test.go:36: 	Test 0:	When handling a city for Sydney.
    TestMutate/city: data_test.go:18: 	✓	Test 0:	Should be able to to see Dgraph is ready.
    TestMutate/city: data_test.go:24: 	✓	Test 0:	Should be able to connect to Dgraph.
    TestMutate/city: data_test.go:37: 	✓	Test 0:	Should be able to drop the data and schema.
    TestMutate/city: data_test.go:40: 	✗	Test 0:	Should be able to create the schema: creating schema: graphql request error: Post "http://0.0.0.0:32784/admin/schema": context deadline exceeded
<snip>
```

I increased the timeout to 30 seconds in mutate_test:38 which "solved" the problem, unless of course part of the test was to check for latency from the server.

**Comment by ardan-bkennedy** [comment]
Sometimes the DB is not ready in time for sure. It is rare but it happens. Why not put in a PR for the change?

**Comment by ardan-bkennedy** [comment]
Actually, that is new. I've never seen that, that should not happen :(

**Comment by matthewmcneely** [comment]
A little more detail. I'm on a branch where I updated the container to 20.03.1 and this error is getting returned:

`mutation updateGQLSchema failed because succeeded in saving GraphQL schema but failed to alter Dgraph schema  because errIndexingInProgress. Please retry (Locations: [{Line: 3, Column: 4}])`

**Comment by ardan-bkennedy** [comment]
Make sure Dgraph was fully stopped and terminated to start. Once you stop the docker-compose you need to run `make down`. If not a volume is left out there.

I pushed some new code to master as well that is using 20.03.1

**Comment by ardan-bkennedy** [comment]
Worse case I will jump on a video chat and you can share your screen.

**Comment by matthewmcneely** [comment]
> Make sure Dgraph was fully stopped and terminated to start

Recall that the tests spawn and use an ephemeral dgraph container which is used for the tests and then summarily destroyed. So no shenanigans with docker-compose should be needed, right?

**Comment by ardan-bkennedy** [comment]
Ok, so this is purely the tests. Right now on your machine the tests fail because it is taking longer for the DB to be ready or it's just not performing :(

Do you want to jump on a video chat?

Make we can clone the latest master to a new folder and try that first?

**Comment by matthewmcneely** [comment]
> Do you want to jump on a video chat?

I can but after 8p EDT. If that's too late no worries, I'll keep plugging along. 

If you'd add me as a contributor (with ability to create/mod branches) I'll push the branch that I'm experimenting on

**Comment by ardan-bkennedy** [comment]
You can fork the project and PR things. I am out of licenses for adding new people :(

**Comment by matthewmcneely** [comment]
Increasing the timeout seems to solve the problem
