### ISSUE TITLE
There is currently no signal propagation happening to the app process

### ISSUE THREAD

**Issue by tullo** [dgraph-io/travel#24]
There is currently no signal propagation happening from the outside (compose/k8s) to the app process running in the container

```
docker-compose exec travel-api sh
/app # pstree 
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c /app/main
    6 root       0:00 /app/main
   19 root       0:00 sh
   25 root       0:00 ps aux
```
main has PID 6 but it should run as PID 1 in order to catch signals like SIGINT, SIGTERM, etc

You can fix this  by using the 'exec' form for image CMD `CMD ["/app/main"]`

**Comment by ardan-bkennedy** [comment]
Can't you explain this more? `exec` form for image CMD?

**Comment by ardan-bkennedy** [comment]
Ok, I got it. Thanks for letting me know. I had no idea.
